

spring:
  datasource:
    name: datasource
    url: jdbc:mysql://192.168.111.60:3306/qiqiim?characterEncoding=UTF-8&amp;characterSetResults=UTF-8&amp;zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: '000000'
    driverClassName: com.mysql.jdbc.Driver
    max-active: 2
    max-idle: 2
    min-idle: 2
    initial-size: 2
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    test-while-idle: false
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 3000
    max-wait: 3000
    jmx-enabled: true
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    jpa:
      repository:
        enabled: true
  redis:
    host: 127.0.0.1
    password: '000000'
    port: 6379
    timeout: 800000
    jedis:
      pool:
        max-wait: 1000000
        max-active: 100
        min-idle: 50
        max-idle: 8


server:
  port: 8089

imWebsocketServer:
  port: 8090

imServer:
  port: 2000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
